const actionTypes = {
  INITIALIZE_APP_START: 'INITIALIZE_APP_START',
  INITIALIZE_APP_SUCCESS: 'INITIALIZE_APP_SUCCESS',
  INITIALIZE_APP_FAILURE: 'INITIALIZE_APP_FAILURE',
  API_EXAMPLE_DATA_CREATE_REQUEST: 'API_EXAMPLE_DATA_CREATE_REQUEST',
  API_EXAMPLE_DATA_CREATE_SUCCESS: 'API_EXAMPLE_DATA_CREATE_SUCCESS',
  API_EXAMPLE_DATA_CREATE_FAILURE: 'API_EXAMPLE_DATA_CREATE_FAILURE',
  API_EXAMPLE_DATA_UPDATE_REQUEST: 'API_EXAMPLE_DATA_UPDATE_REQUEST',
  API_EXAMPLE_DATA_UPDATE_SUCCESS: 'API_EXAMPLE_DATA_UPDATE_SUCCESS',
  API_EXAMPLE_DATA_UPDATE_FAILURE: 'API_EXAMPLE_DATA_UPDATE_FAILURE',
};

export default actionTypes;
